kunpengcompute/devkitdemo

Hyper_tuner/testdemo/falsesharing/falsesharing_mod.c
Kunpeng L3 cacheline 128 byte, so align with 128byte
=> Modify alignment number of byte

Hyper_tuner/testdemo/io/io_continuum.c
=> Add IO demo

Porting_advisor/testdemo/code_migration/code/Makefile, Porting_advisor/testdemo/code_migration/code/file_lock.c, Porting_advisor/testdemo/code_migration/code/file_lock.h, Porting_advisor/testdemo/code_migration/code/interface.s, Porting_advisor/testdemo/code_migration/code/ksw.c, Porting_advisor/testdemo/code_migration/code/ksw.h, Porting_advisor/testdemo/code_migration/code_mod/Makefile, Porting_advisor/testdemo/code_migration/code_mod/file_lock.c, Porting_advisor/testdemo/code_migration/code_mod/file_lock.h, Porting_advisor/testdemo/code_migration/code_mod/interface.s, Porting_advisor/testdemo/code_migration/code_mod/ksw.c, Porting_advisor/testdemo/code_migration/code_mod/ksw.h
=> 鲲鹏代码迁移工具demo增加license声明

Porting_advisor/testdemo/asm_trans/all_asm/Makefile, Porting_advisor/testdemo/asm_trans/all_asm/main.c, Porting_advisor/testdemo/asm_trans/all_asm/test.s, Porting_advisor/testdemo/asm_trans/mult_inline_asm/gcd.c, Porting_advisor/testdemo/asm_trans/single_inline_asm/swap.c, Porting_advisor/testdemo/weak_consistency/atomic/Makefile, Porting_advisor/testdemo/weak_consistency/atomic/atomic.cpp, Porting_advisor/testdemo/weak_consistency/common/Makefile, Porting_advisor/testdemo/weak_consistency/common/common.c, Porting_advisor/testdemo/weak_consistency/lock/Makefile, Porting_advisor/testdemo/weak_consistency/lock/lock.c
add demo for asm_trans & weak_consistency
=> add demo for asm_trans & weak_consistency

Porting_advisor/testdemo/precheck/Makefile, Porting_advisor/testdemo/precheck/func001.c, Porting_advisor/testdemo/precheck/func002.c, Porting_advisor/testdemo/precheck/func003.c, Porting_advisor/testdemo/precheck/func004.c
=> 上传devkit鲲鹏代码迁移工具的64位预检功能的demo

sc-sdk/examples/data-sealing/CA/cloud/CMakeLists.txt, sc-sdk/examples/data-sealing/CA/data_sealing_ca.c, sc-sdk/examples/data-sealing/CA/data_sealing_ca.h, sc-sdk/examples/data-sealing/CA/install.sh, sc-sdk/examples/data-sealing/README.md, sc-sdk/examples/data-sealing/TA/cloud/CMakeLists.txt, sc-sdk/examples/data-sealing/TA/cloud/config_cloud.ini, sc-sdk/examples/data-sealing/TA/data_sealing_ta.c, sc-sdk/examples/data-sealing/TA/data_sealing_ta.h, sc-sdk/examples/data-sealing/TA/install.sh, sc-sdk/examples/data-sealing/TA/manifest.txt
=> add kunpeng itrustee data-sealing demo

sc-sdk/examples/data-sealing/CA/data_sealing_ca.c
=> 修改CA读取文件超过最大值没有提示的问题

sc-sdk/examples/data-sealing/CA/data_sealing_ca.c
=> Optimize help information format.

sc-sdk/examples/secret-vote/service/requirements.txt, sc-sdk/examples/secret-vote/service/service/settings.py, sc-sdk/examples/secret-vote/service/vote/management/commands/init_db.py, sc-sdk/examples/secret-vote/service/vote/utils.py
Fix incorrect url bugs and add requirements.txt
=> Fix incorrect url bugs and add requirements.txt

sc-sdk/examples/secret-vote/CA/CMakeLists.txt, sc-sdk/examples/secret-vote/CA/secret_vote_ca.c, sc-sdk/examples/secret-vote/CA/secret_vote_ca.h, sc-sdk/examples/secret-vote/README.md, sc-sdk/examples/secret-vote/TA/CMakeLists.txt, sc-sdk/examples/secret-vote/TA/config.mk, sc-sdk/examples/secret-vote/TA/config_cloud.ini, sc-sdk/examples/secret-vote/TA/manifest.txt, sc-sdk/examples/secret-vote/TA/secret_vote_ta.c, sc-sdk/examples/secret-vote/TA/secret_vote_ta.h, sc-sdk/examples/secret-vote/build/build_ca.sh, sc-sdk/examples/secret-vote/build/install_ta.sh, sc-sdk/examples/secret-vote/build/uninstall_ta.sh
=> add TA & CA

sc-sdk/examples/secret-vote/CA/CMakeLists.txt, sc-sdk/examples/secret-vote/CA/secret_vote_ca.c, sc-sdk/examples/secret-vote/CA/secret_vote_ca.h, sc-sdk/examples/secret-vote/README.md, sc-sdk/examples/secret-vote/TA/CMakeLists.txt, sc-sdk/examples/secret-vote/TA/secret_vote_ta.c, sc-sdk/examples/secret-vote/TA/secret_vote_ta.h, sc-sdk/examples/secret-vote/build/build_ca.sh, sc-sdk/examples/secret-vote/build/install_ta.sh, sc-sdk/examples/secret-vote/build/uninstall_ta.sh, sc-sdk/examples/secret-vote/service/service/urls.py, sc-sdk/examples/secret-vote/service/vote/management/commands/init_db.py, sc-sdk/examples/secret-vote/service/vote/utils.py, sc-sdk/examples/secret-vote/service/vote/views.py
=> 优化代码结构和异常提示，增加指针和参数校验

sc-sdk/examples/secret-vote/README.md, sc-sdk/examples/secret-vote/README_en.md, sc-sdk/examples/secret-vote/service/manage.py
=> add version check

sc-sdk/examples/secret-vote/CA/secret_vote_ca.c
=> 修复读取公钥状态判断错误问题

Development_framework/gpc-sdk/examples/crc32/CMakeLists.txt, Development_framework/gpc-sdk/examples/crc32/README.md, Development_framework/gpc-sdk/examples/crc32/README_en.md, Development_framework/gpc-sdk/examples/crc32/src/crc32_demo.c, Development_framework/gpc-sdk/examples/crc32/src/crc32_neon_demo.c
=> add crc32 demo

Development_framework/gpc-sdk/examples/crc32/CMakeLists.txt, Development_framework/gpc-sdk/examples/crc32/README.md, Development_framework/gpc-sdk/examples/crc32/README_en.md, Development_framework/gpc-sdk/examples/crc32/inc/crc32_demo.h, Development_framework/gpc-sdk/examples/crc32/inc/crc32_neon_demo.h, Development_framework/gpc-sdk/examples/crc32/src/crc32_demo.c, Development_framework/gpc-sdk/examples/crc32/src/crc32_neon_demo.c, Development_framework/gpc-sdk/examples/crc32/src/main.c
=> update crc32 demo

Development_framework/gpc-sdk/examples/aes/CMakeLists.txt, Development_framework/gpc-sdk/examples/aes/README.md, Development_framework/gpc-sdk/examples/aes/README_en.md, Development_framework/gpc-sdk/examples/aes/include/aes.h, Development_framework/gpc-sdk/examples/aes/include/aesv8-armx.h, Development_framework/gpc-sdk/examples/aes/include/arm_arch.h, Development_framework/gpc-sdk/examples/aes/src/aes.c, Development_framework/gpc-sdk/examples/aes/src/aesv8-armx.S, Development_framework/gpc-sdk/examples/aes/src/openssl.c, Development_framework/gpc-sdk/examples/aes/src/wd.c, Development_framework/gpc-sdk/examples/aes/test_data/aes.txt
=> add aes demo

Development_framework/gpc-sdk/examples/aes/src/openssl.c
=> fix aes cfb and ofb error

Development_framework/gpc-sdk/examples/aes/README.md, Development_framework/gpc-sdk/examples/aes/README_en.md, Development_framework/gpc-sdk/examples/aes/include/aes.h, Development_framework/gpc-sdk/examples/aes/src/aes.c, Development_framework/gpc-sdk/examples/aes/src/openssl.c, Development_framework/gpc-sdk/examples/aes/src/wd.c, Development_framework/gpc-sdk/examples/sm3/src/sm3_demo.c, Development_framework/gpc-sdk/examples/sm3/src/wd_sm3.c, Development_framework/gpc-sdk/examples/sm4/README.md, Development_framework/gpc-sdk/examples/sm4/README_en.md, Development_framework/gpc-sdk/examples/sm4/include/option.h, Development_framework/gpc-sdk/examples/sm4/src/e_sm4.c, Development_framework/gpc-sdk/examples/sm4/src/sm4_demo.c, Development_framework/gpc-sdk/examples/sm4/src/wd_sm4.c
=> Code optimization

Development_framework/gpc-sdk/examples/aes/src/aes.c, Development_framework/gpc-sdk/examples/sm4/src/sm4_demo.c
=> fix key length validate error

Development_framework/gpc-sdk/examples/aes/src/aes.c
=> fix compile warning

Development_framework/gpc-sdk/examples/kae_aes/CMakeLists.txt, Development_framework/gpc-sdk/examples/kae_sm3/CMakeLists.txt, Development_framework/gpc-sdk/examples/kae_sm4/CMakeLists.txt, Development_framework/gpc-sdk/examples/kaezip/CMakeLists.txt, Development_framework/gpc-sdk/examples/kaezip/src/kaezip_demo.c
=> add lib path

sc-sdk/build/patch/centos/itrustee_client/0001-add-link-to-so.patch, sc-sdk/build/patch/centos/itrustee_sdk/0001-add-link-to-so.patch, sc-sdk/build/patch/centos/itrustee_tzdriver/0001-add-link-to-so-and-update-kernel-path.patch, sc-sdk/build/patch/centos/libboundscheck/0001-add-link-to-so.patch, sc-sdk/build/patch/openEuler/itrustee_client/0001-add-link-to-so.patch, sc-sdk/build/patch/openEuler/itrustee_sdk/0001-add-link-to-so.patch, sc-sdk/build/patch/openEuler/itrustee_tzdriver/0001-add-link-to-so-and-update-kernel-path.patch, sc-sdk/build/patch/openEuler/libboundscheck/0001-add-link-to-so.patch, sc-sdk/build/patch/uos/itrustee_client/0001-add-link-to-so.patch, sc-sdk/build/patch/uos/itrustee_sdk/0001-add-link-to-so.patch, sc-sdk/build/patch/uos/itrustee_tzdriver/0001-adapt-modify-in-uos.patch, sc-sdk/build/patch/uos/itrustee_tzdriver/0002-update-kernel-path.patch, sc-sdk/build/patch/uos/libboundscheck/0001-add-link-to-so.patch, sc-sdk/build/script/centos/spec/kunpeng-sc-devel.spec, sc-sdk/build/script/centos/spec/kunpeng-sc.spec, sc-sdk/build/script/openEuler/spec/kunpeng-sc-devel.spec, sc-sdk/build/script/openEuler/spec/kunpeng-sc.spec, sc-sdk/build/script/package.sh, sc-sdk/build/script/uos/kunpeng-sc-devel/buildroot/DEBIAN/control, sc-sdk/build/script/uos/kunpeng-sc-devel/script/create-kunpeng-sc-devel-pkg.sh, sc-sdk/build/script/uos/kunpeng-sc/buildroot/DEBIAN/control, sc-sdk/build/script/uos/kunpeng-sc/script/create-kunpeng-sc-pkg.sh
=> update patch and sdk version

sc-sdk/examples/cert-assign/CA/cert_assign_ca.c
=> fix save file bug

sc-sdk/examples/cert-assign/CA/CMakeLists.txt, sc-sdk/examples/cert-assign/CA/cert_assign_ca.c, sc-sdk/examples/cert-assign/CA/cert_assign_ca.h, sc-sdk/examples/cert-assign/README.md, sc-sdk/examples/cert-assign/README_en.md, sc-sdk/examples/cert-assign/TA/CMakeLists.txt, sc-sdk/examples/cert-assign/TA/cert_assign_ta.c, sc-sdk/examples/cert-assign/TA/cert_assign_ta.h
=> optimization cert assign demo

Development_framework/gpc-sdk/examples/ZSTD/README.md, Development_framework/gpc-sdk/examples/ZSTD/README_en.md, Development_framework/gpc-sdk/examples/hyperscan/README.md, Development_framework/gpc-sdk/examples/hyperscan/README_en.md, Development_framework/gpc-sdk/examples/kaezip/README.md, Development_framework/gpc-sdk/examples/kaezip/README_en.md, Development_framework/gpc-sdk/examples/snappy/README.md, Development_framework/gpc-sdk/examples/snappy/README_en.md
=> fix issue 通用SDK实现demo的优化

hpc-sdk/examples/hmpi/bcast/CMakeLists.txt, hpc-sdk/examples/kml/blas/CMakeLists.txt, hpc-sdk/examples/kml/blas/README.md, hpc-sdk/examples/kml/blas/README_en.md, hpc-sdk/examples/kml/fft/CMakeLists.txt, hpc-sdk/examples/kml/fft/README.md, hpc-sdk/examples/kml/fft/README_en.md, hpc-sdk/examples/kml/lapack/CMakeLists.txt, hpc-sdk/examples/kml/math/CMakeLists.txt, hpc-sdk/examples/kml/math/README.md, hpc-sdk/examples/kml/math/README_en.md, hpc-sdk/examples/kml/spblas/CMakeLists.txt, hpc-sdk/examples/kml/spblas/README.md, hpc-sdk/examples/kml/spblas/README_en.md
add compile options and update README
=> add compile options and update README

hpc-sdk/examples/kml/blas/README.md, hpc-sdk/examples/kml/blas/README_en.md, hpc-sdk/examples/kml/fft/README.md, hpc-sdk/examples/kml/fft/README_en.md, hpc-sdk/examples/kml/math/README.md, hpc-sdk/examples/kml/math/README_en.md, hpc-sdk/examples/kml/spblas/README.md, hpc-sdk/examples/kml/spblas/README_en.md
=> 修改readme中关于版本的描述

Development_framework/dpak-sdk/build/build.sh, Development_framework/dpak-sdk/build/build_dev.sh, Development_framework/dpak-sdk/build/build_runtime.sh, Development_framework/dpak-sdk/build/download_package.sh, Development_framework/dpak-sdk/build/download_src.sh
=> add dpak build script

Development_framework/gpc-sdk/examples/kaezip/README.md, Development_framework/gpc-sdk/examples/kaezip/README_en.md, Development_framework/hpc-sdk/examples/kml/blas/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/fft/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/lapack/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/math/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/spblas/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/spblas/README_en.md
1、hpc CMakeLists.txt存在错误
2、gpc kaezip readme错误修复
=> 修复CMakeLists.txt问题和字符错误

Development_framework/hpc-sdk/examples/helloworld/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/blas/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/fft/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/lapack/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/math/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/spblas/CMakeLists.txt
=> 修改编译选项o0->O0

Hyper_tuner/testdemo/基于java性能分析工具的锁竞争定位调优实践/Lock.java
=> 锁竞争调优demo样例修改

Development_framework/gpc-sdk/examples/ZSTD/CMakeLists.txt, Development_framework/gpc-sdk/examples/aes/CMakeLists.txt, Development_framework/gpc-sdk/examples/crc32/CMakeLists.txt, Development_framework/gpc-sdk/examples/hyperscan/CMakeLists.txt, Development_framework/gpc-sdk/examples/kae_aes/CMakeLists.txt, Development_framework/gpc-sdk/examples/kae_sm3/CMakeLists.txt, Development_framework/gpc-sdk/examples/kae_sm4/CMakeLists.txt, Development_framework/gpc-sdk/examples/kaezip/CMakeLists.txt, Development_framework/gpc-sdk/examples/sha256/CMakeLists.txt, Development_framework/gpc-sdk/examples/snappy/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/blas/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/fft/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/lapack/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/math/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/spblas/CMakeLists.txt
1、gpc 样例增加编译类型和-g编译选项支持调试
2、hpc 样例去除-O0选项，避免误会
=> gpc demo增加-g编译选项支持调试，hpc demo 去除-O0选项

Development_framework/hpc-sdk/examples/helloworld/CMakeLists.txt
=> 删除helloworld-O0选项

Development_framework/hpc-sdk/examples/hmpi/bcast/CMakeLists.txt, Development_framework/hpc-sdk/examples/hmpi/bcast/src/bcast_demo.c
=> hmpi demo增加分组和允许调试

hpc-sdk/examples/hmpi/bcast/CMakeLists.txt, hpc-sdk/examples/hmpi/bcast/src/bcast_demo.c
=> 修改原有的hpcdemo支持调试和分组

hpc-sdk/examples/hmpi/bcast/src/bcast_demo.c
2.5.2分支 hpc bcast demo 增加分组调试功能
=> 2.5.2分支 hpc bcast demo 增加分组调试功能

Development_framework/gpc-sdk/examples/haf/README.md, Development_framework/gpc-sdk/examples/haf/README_en.md, Development_framework/gpc-sdk/examples/haf/pom.xml
update haf project Readme and pom.xml
=> update haf project Readme and pom.xml

Development_framework/hpc-sdk/examples/kml/fft/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/fft/src/fft_demo.c
=> 修改FFT Demo单精度版本接口与双精度版本不同

Hyper_tuner/testdemo/java_perf_test/README.md, Hyper_tuner/testdemo/java_perf_test/pom.xml, Hyper_tuner/testdemo/基于java性能分析工具的GC日志调优实践/README.md, Hyper_tuner/testdemo/基于java性能分析工具的热点函数定位调优实践/README.md
=> readme文件修改

Hyper_tuner/testdemo/lock/pthread_atomic.c, Hyper_tuner/testdemo/锁性能调优实践/pthread_atomic.c
delete some no use demo code in lock module
=> discard no use <threads.h>

sc-sdk/examples/hello-world/CA/CMakeLists.txt, sc-sdk/examples/hello-world/CA/hello_world_ca.c, sc-sdk/examples/hello-world/CA/hello_world_ca.h, sc-sdk/examples/hello-world/CA/install.sh, sc-sdk/examples/hello-world/CA/uninstall.sh, sc-sdk/examples/hello-world/README.md, sc-sdk/examples/hello-world/README_en.md, sc-sdk/examples/hello-world/TA/CMakeLists.txt, sc-sdk/examples/hello-world/TA/config.mk, sc-sdk/examples/hello-world/TA/config_cloud.ini, sc-sdk/examples/hello-world/TA/hello_world_ta.c, sc-sdk/examples/hello-world/TA/hello_world_ta.h, sc-sdk/examples/hello-world/TA/install.sh, sc-sdk/examples/hello-world/TA/manifest.txt, sc-sdk/examples/hello-world/TA/uninstall.sh
=> add TEE hello-world demo

Development_framework/gpc-sdk/examples/haf/src/main/java/com/demo/HafDemo.java
=> 修改 HAF demo适配1.3版本

Development_framework/gpc-sdk/examples/haf/src/main/java/com/demo/HafDemo.java
=> 修改HAF demo适配1.3版本

Development_framework/sc-sdk/examples/CA/README.md, Development_framework/sc-sdk/examples/CA/README_en.md, Development_framework/sc-sdk/examples/RSA/README.md, Development_framework/sc-sdk/examples/RSA/README_en.md, Development_framework/sc-sdk/examples/RSA/TA/cloud/CMakeLists.txt, Development_framework/sc-sdk/examples/RSA/TA/cloud/config_cloud.ini, Development_framework/sc-sdk/examples/TA/README.md, Development_framework/sc-sdk/examples/TA/README_en.md, Development_framework/sc-sdk/examples/TA/cloud/CMakeLists.txt, Development_framework/sc-sdk/examples/TA/cloud/config_cloud.ini, Development_framework/sc-sdk/examples/cert-assign/README.md, Development_framework/sc-sdk/examples/cert-assign/README_en.md, Development_framework/sc-sdk/examples/cert-assign/TA/CMakeLists.txt, Development_framework/sc-sdk/examples/cert-assign/TA/config_cloud.ini, Development_framework/sc-sdk/examples/data-sealing/README.md, Development_framework/sc-sdk/examples/data-sealing/README_en.md, Development_framework/sc-sdk/examples/data-sealing/TA/cloud/CMakeLists.txt, Development_framework/sc-sdk/examples/data-sealing/TA/cloud/config_cloud.ini, Development_framework/sc-sdk/examples/hello-world/README.md, Development_framework/sc-sdk/examples/hello-world/README_en.md, Development_framework/sc-sdk/examples/hello-world/TA/CMakeLists.txt, Development_framework/sc-sdk/examples/hello-world/TA/config_cloud.ini, Development_framework/sc-sdk/examples/secret-vote/README.md, Development_framework/sc-sdk/examples/secret-vote/README_en.md, Development_framework/sc-sdk/examples/secret-vote/TA/CMakeLists.txt, Development_framework/sc-sdk/examples/secret-vote/TA/config_cloud.ini, Development_framework/sc-sdk/examples/secret-vote/TA/secret_vote_ta.h
update demo for kunpeng-sc-1.3.0
=> update demo for kunpeng-sc-1.3.0

Hyper_tuner/testdemo/Know-how/core_bound.c, Hyper_tuner/testdemo/Know-how/memory_bound.c, Hyper_tuner/testdemo/Know-how/omp_utilization.c, Hyper_tuner/testdemo/Know-how/send_recv.cpp, Hyper_tuner/testdemo/Know-how/serial_time.c, Hyper_tuner/testdemo/Know-how/socket_bandwidth.c, Hyper_tuner/testdemo/Know-how/utils.h
add utils.h required for compiling demo, and fix some bug of demo
=> add utils.h & fix demo bug

Development_framework/sc-sdk/examples/hello-world/TA/hello_world_ta.c
=> fix unused variable warning

Development_framework/sc-sdk/build/script/package.sh, Development_framework/sc-sdk/examples/CA/cloud/CMakeLists.txt, Development_framework/sc-sdk/examples/RSA/CA/cloud/CMakeLists.txt, Development_framework/sc-sdk/examples/cert-assign/CA/CMakeLists.txt, Development_framework/sc-sdk/examples/cert-assign/README.md, Development_framework/sc-sdk/examples/cert-assign/README_en.md, Development_framework/sc-sdk/examples/data-sealing/CA/cloud/CMakeLists.txt, Development_framework/sc-sdk/examples/hello-world/CA/CMakeLists.txt, Development_framework/sc-sdk/examples/secret-vote/CA/CMakeLists.txt
=> del libteec_adaptor.so

Development_framework/gpc-sdk/examples/haf/README.md, Development_framework/gpc-sdk/examples/haf/README_en.md
=> Update haf README.md

Development_framework/sc-sdk/examples/hello-world/README_en.md, Development_framework/sc-sdk/examples/java-hello-world/README.md, Development_framework/sc-sdk/examples/java-hello-world/README_en.md, Development_framework/sc-sdk/examples/java-hello-world/src/HelloWorld.java
=> add TEE java demo

Development_framework/sc-sdk/examples/python-ml-titanic/README.md, Development_framework/sc-sdk/examples/python-ml-titanic/input/test.csv, Development_framework/sc-sdk/examples/python-ml-titanic/input/train.csv, Development_framework/sc-sdk/examples/python-ml-titanic/titanic/titanic.py
add python machine learning titanic demo
=> add python ml titanic demo

Development_framework/sc-sdk/examples/java-hello-world/sign.sh, Development_framework/sc-sdk/examples/java-hello-world/src/HelloWorld.java, Development_framework/sc-sdk/examples/python-ml-titanic/sign.sh
=> TEE 高级语言demo优化

devops/jenkins-plugin/porting-advisor-plugin/pom.xml, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/PortingAdvisorBuilder.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/slavecopy/CopyToSlaveBuildWrapper.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/slavecopy/MyFilePath.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/utils/BashCmdExec.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/utils/HttpRequest.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/utils/ParameterFmt.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/utils/SourceScanParamsFmt.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/webserver/APIClient.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/webserver/ApiInfo.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/webserver/PortadvAffinityAnalysis.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/webserver/PortadvBinaryProcess.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/webserver/SourceCodeMigration.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/webserver/SrvType.java, devops/jenkins-plugin/porting-advisor-plugin/src/main/java/io/jenkins/plugins/devkit/webserver/UserAccount.java
=> Jenkins插件代码合入:1.0.0

Development_framework/sc-sdk/build/patch/openEuler/itrustee_client/0001-add-link-to-so.patch, Development_framework/sc-sdk/build/patch/openEuler/itrustee_sdk/0001-add-link-to-so.patch, Development_framework/sc-sdk/build/patch/openEuler/itrustee_tzdriver/0001-add-link-to-so-and-update-kernel-path.patch, Development_framework/sc-sdk/build/script/openEuler/spec/kunpeng-sc-devel.spec, Development_framework/sc-sdk/build/script/openEuler/spec/kunpeng-sc.spec, Development_framework/sc-sdk/build/script/package.sh, Development_framework/sc-sdk/examples/python-ml-titanic/README.md, Development_framework/sc-sdk/examples/python-ml-titanic/build_mllib/build_joblib.sh, Development_framework/sc-sdk/examples/python-ml-titanic/build_mllib/build_numpy.sh, Development_framework/sc-sdk/examples/python-ml-titanic/build_mllib/build_openblas.sh, Development_framework/sc-sdk/examples/python-ml-titanic/build_mllib/build_pandas.sh, Development_framework/sc-sdk/examples/python-ml-titanic/build_mllib/build_scipy.sh, Development_framework/sc-sdk/examples/python-ml-titanic/build_mllib/build_sklearn.sh, Development_framework/sc-sdk/examples/python-ml-titanic/build_mllib/build_xgboost.sh, Development_framework/sc-sdk/examples/python-ml-titanic/build_mllib/common.sh
add kunpeng-sc 2.0 build script
=> add kunpeng-sc 2.0 build script

hpc-sdk/examples/kml/blas/CMakeLists.txt, hpc-sdk/examples/kml/blas/README.md, hpc-sdk/examples/kml/blas/README_en.md, hpc-sdk/examples/kml/fft/CMakeLists.txt, hpc-sdk/examples/kml/fft/README.md, hpc-sdk/examples/kml/fft/README_en.md, hpc-sdk/examples/kml/lapack/CMakeLists.txt, hpc-sdk/examples/kml/lapack/README.md, hpc-sdk/examples/kml/lapack/README_en.md, hpc-sdk/examples/kml/math/CMakeLists.txt, hpc-sdk/examples/kml/math/README.md, hpc-sdk/examples/kml/math/README_en.md, hpc-sdk/examples/kml/spblas/CMakeLists.txt, hpc-sdk/examples/kml/spblas/README.md, hpc-sdk/examples/kml/spblas/README_en.md
更新CMakeLists.txt里的KML_PATH，并更新README文件
=> update kml path

Development_framework/hpc-sdk/examples/kml/blas/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/blas/README.md, Development_framework/hpc-sdk/examples/kml/blas/README_en.md, Development_framework/hpc-sdk/examples/kml/fft/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/fft/README.md, Development_framework/hpc-sdk/examples/kml/fft/README_en.md, Development_framework/hpc-sdk/examples/kml/lapack/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/lapack/README.md, Development_framework/hpc-sdk/examples/kml/lapack/README_en.md, Development_framework/hpc-sdk/examples/kml/math/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/math/README.md, Development_framework/hpc-sdk/examples/kml/math/README_en.md, Development_framework/hpc-sdk/examples/kml/spblas/CMakeLists.txt, Development_framework/hpc-sdk/examples/kml/spblas/README.md, Development_framework/hpc-sdk/examples/kml/spblas/README_en.md
update Development_framework kml path
=> update Development_framework kml path

Compiler_and_Debugger/mpi_demo/bcast_demo.c, Compiler_and_Debugger/mpi_demo/mpi_openmp_demo.c
=> Devkitdemo 23.0.1

Development_framework/gpc-sdk/examples/haf/README.md, Development_framework/gpc-sdk/examples/haf/README_en.md, Development_framework/gpc-sdk/examples/hyperscan/README.md, Development_framework/gpc-sdk/examples/hyperscan/README_en.md, Development_framework/gpc-sdk/examples/kae_aes/README.md, Development_framework/gpc-sdk/examples/kae_aes/README_en.md, Development_framework/gpc-sdk/examples/kae_sm3/README.md, Development_framework/gpc-sdk/examples/kae_sm3/README_en.md, Development_framework/gpc-sdk/examples/kae_sm4/README.md, Development_framework/gpc-sdk/examples/kae_sm4/README_en.md, Development_framework/gpc-sdk/examples/kaezip/README.md, Development_framework/gpc-sdk/examples/kaezip/README_en.md
update help info of gpc-sdk demos because update kae
=> update help info of gpc-sdk demos
